ALTER TABLE guests ADD COLUMN IF NOT EXISTS is_room_revealed BOOLEAN DEFAULT false;

CREATE TABLE IF NOT EXISTS faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE faqs DISABLE ROW LEVEL SECURITY;

-- Delete existing to make this script re-runnable without duplicates
TRUNCATE TABLE faqs;

INSERT INTO faqs (category, question, answer, display_order) VALUES
('📅 Itinerary & Schedule', 'What time should I arrive on the first day?', 'We will be welcoming guests from 5:00 PM onwards.', 1),
('📅 Itinerary & Schedule', 'What time does everything wrap up on the final day?', 'Guests need to check out by 10:30 AM.', 2),
('📅 Itinerary & Schedule', 'Are there any gaps between events where we can explore Devon?', 'You are welcome to explore Devon in the mornings, or you can join us for the optional morning activities we will be hosting.', 3),

('📍 Logistics', 'What is the exact address of the venue?', 'Huntsham Court, Huntsham, Tiverton EX16 7NA.', 4),
('📍 Logistics', 'Is there parking available on-site, and is it free?', 'Yes, there is plenty of parking available free of charge.', 5),
('📍 Logistics', 'Can I leave my car at the venue overnight?', 'Of course! You are welcome to leave your vehicle parked at the venue overnight.', 6),
('📍 Logistics', 'What is the closest train station to the venue?', 'Tiverton Parkway offers express links to London (1 hour 55 minutes), Bristol (45 minutes), and Exeter (15 minutes), and is just a 12-minute taxi ride from Huntsham Court. Postcode EX16 7NA will lead you directly to the entrance.', 7),
('📍 Logistics', 'How easy is it to get a taxi in the area?', 'We highly recommend booking taxis in advance as Huntsham is in a rural area and taxis can be hard to come by on the spot.', 8),
('📍 Logistics', 'Do you have numbers for local taxi companies we should pre-book?', 'Yes, please pre-book with any of the following: A-2-B Taxis (01884 251 252), RT Taxis (07731 154 024), Rick’s Private Hire (07789 998 224), Brian’s Taxi (07753 791 810), Liz Cabs (07899 903 314), Parkway Taxis (01884 388 99), Devon Transfers Private Hire (07425 262 087), Chris Cars (07773 600 125), Hero 2 Transport (01884 212 447).', 9),
('📍 Logistics', 'Is there reliable phone signal or Wi-Fi at the venue?', 'Yes, Wi-Fi is available throughout the property.', 10),
('📍 Logistics', 'Is the venue wheelchair accessible / suitable for those with limited mobility?', 'Yes. The venue is accessible; please request a downstairs bedroom if needed by contacting Rosh or Harry.', 11),
('📍 Logistics', 'What happens if it rains? Is there an indoor backup plan?', 'We are crossing our fingers for good weather! However, we have a complete indoor backup plan ready if needed.', 12),

('🛏️ Accommodation', 'What nearby hotels, B&Bs, or Airbnbs do you recommend?', 'We recommend the Hartnoll Hotel (Tiverton, 6m), Lawpit Lodges (Tiverton, 6m), Three Gates Farm (Huntsham, 1.5m), Weston House Devon (Bampton, 4m), Bishops Barton (Greenham, 5m), Travelodge (Sampford Peverell, 5m), Brambles Bed and Breakfast (Sampford Peverell, 5m), Berry House and Farm (Shillingford, 4m), Waterside House (Uplowman, 3m), Old Mill Cottages (Shillingford, 3m), or Cottage for Two (Staple Cross, 2.5m).', 13),
('🛏️ Accommodation', 'When is the deadline to book our accommodation?', 'Payment needs to be received by December 1st to secure your room.', 14),
('🛏️ Accommodation', 'Is there a swimming pool, hot tub, or beach access nearby we should pack for?', 'No, unfortunately there is no swimming pool or hot tub on-site.', 15),

('👗 Dress Code', 'What is the dress code for Day 1?', 'Summer cocktail party. Dresses, skirts, and jeans are all welcome. Trainers are fine.', 16),
('👗 Dress Code', 'What is the dress code for Day 2?', 'Garden party. Florals, sandals, shorts, polos, and T-shirts are all fine. Trainers are also allowed, as we will be playing games.', 17),
('👗 Dress Code', 'What is the dress code for Day 3?', 'Wedding day attire! Typical summer wedding. Ties are not mandatory. Please, no jeans or trainers.', 18),
('👗 Dress Code', 'Will any part of the wedding be on grass, pebbles, or sand? (Important for heel choice!)', 'Yes. There is a lot of grass on the croquet lawn and in the gardens, so please select your footwear accordingly.', 19),
('👗 Dress Code', 'Should I bring warm layers for the evening?', 'We suggest checking the weather forecast beforehand. Since some evening events will be held outdoors, we recommend bringing warm layers just in case.', 20),

('🍽️ Food & Drink', 'Which meals are being provided over the three days?', 'We are providing pizza, a picnic lunch (dips, crisps, sausage rolls, etc.), a BBQ (hot dogs, burgers, salads), and fajitas. Breakfast is provided for those staying on-site, consisting of a spread of sausage/bacon rolls, yoghurt, fruit, granola, tea, and coffee. Snacks will also be available in the Butler’s Pantry throughout the weekend.', 21),
('🍽️ Food & Drink', 'Which meals or drinks do we need to pay for ourselves?', 'None, everything is included!', 22),
('🍽️ Food & Drink', 'Is there a cash bar, or can we pay by card/contactless?', 'All drinks are included throughout the weekend.', 23),
('🍽️ Food & Drink', 'Can I bring my own alcohol or drinks to the venue?', 'We will be providing plenty of drinks; however, you are more than welcome to bring any specific drinks of your own. We suggest keeping these in your rooms so they do not get mixed up with the provided options.', 24),

('👶 Children & Plus-Ones', 'Is babysitting or a crèche available at the venue?', 'No, babysitting or crèche services are not provided.', 25),
('👶 Children & Plus-Ones', 'Can I bring a plus-one?', 'Please do not bring a plus-one; only guests named on the invitations are invited.', 26),
('👶 Children & Plus-Ones', 'My partner’s name wasn’t on the invite, can they still come?', 'All invited guests are named on the invitations. Please message either Rosh or Harry if you would like to double check.', 27),

('🎁 RSVPs & Gifts', 'When is the RSVP deadline?', 'The RSVP deadline is February 7th, 2027.', 28),
('🎁 RSVPs & Gifts', 'How do I RSVP for the different days?', 'Please update your RSVP form on our website.', 29),
('🎁 RSVPs & Gifts', 'Do you have a wedding gift registry or a wishing well?', 'We will be setting up a donation link towards our honeymoon.', 30),
('🎁 RSVPs & Gifts', 'Where can I find your gift registry link?', 'Details will be included on the website.', 31),

('📸 Photos & Fun', 'Can I take photos and videos during the ceremony?', 'We have a professional photographer and content creator capturing the entire ceremony. Please turn off your phones and keep them tucked away during this time.', 32),
('📸 Photos & Fun', 'Can we bring confetti, and does it need to be biodegradable?', 'We will be providing confetti; please do not bring your own.', 33),
('📸 Photos & Fun', 'Is there a theme for the weekend?', 'Fun!', 34),
('📸 Photos & Fun', 'Are pets allowed at the venue?', 'No, please do not bring pets to the venue.', 35),

('🚨 Contacts & Help', 'Who should I contact on the day if I get lost or have an emergency?', 'Please do NOT contact the bride or groom. If you need assistance, please contact Natalie (our coordinator) or a member of the bridal party.', 36),
('🚨 Contacts & Help', 'Who should I ask questions prior to the event?', 'Either Rosh or Harry is on hand to answer any queries you may have prior to the event.', 37),
('🚨 Contacts & Help', 'Who can I ask questions to during the event regarding logistics and timings etc?', 'Please refrain from asking Rosh or Harry questions during the weekend. If anything is unclear, we will have our coordinator Natalie on site, or you can ask a member of the bridal party.', 38);
